### ISSUE TITLE
Graphs in dashboard appear stretched on firefox

### ISSUE THREAD

**Issue by aadilayub** [Emilia-Capital/progress-planner#117]
* [x] I've read and understood the [contribution guidelines](https://github.com/Emilia-Capital/.github/blob/main/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened
The graphs in the progress planner dashboard overflow their containers on firefox

#### Step-by-step reproduction instructions
1. Install the plugin on a fresh wordpress site
2. Open the dashboard in firefox browser

#### Expected results
1. The graphs look proportional

#### Actual results
1. The graphs are stretched and overflow their containers

### Screenshots, screen recording, code snippet
![Image](https://github.com/user-attachments/assets/68af7227-e332-4170-a872-036595e7300b)

### Technical info
* Which browser is affected (or browsers): 
- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Other: 

#### Used versions
* Device you are using: Thinkpad laptop
* Operating system: Fedora 41
* PHP version: 8.2
* WordPress version: 6.6.2 
* WordPress Theme: Twenty Twenty Two

**Comment by aristath** [comment]
Hey there @aadilayub, thank you for reporting this!
I tested this on Firefox, and at first, I was unable to replicate the issue.
I kept refreshing the page until finally at some point I encountered the issue, however, it was completely random... Refreshing the page again resolved it.

Is this something that happens _consistently_ on your end? Does refreshing the page resolve it? 🤔

**Comment by aadilayub** [comment]
@aristath hmm ok now that you mention it, it only happens on the [specific firefox based browser I'm using](zen-browser.app), and goes away when I resize the window. It does happen on every page load though.

**Comment by ilicfilip** [comment]
@aristath , as far I remember this is fixed?

**Comment by aristath** [comment]
Yes, this was fixed in v1.0 after a complete refactor of the graphs 👍
