### ISSUE TITLE
Make a task for filling out the settings page

### ISSUE THREAD

**Issue by jdevalk** [Emilia-Capital/progress-planner#154]
The settings page is something nobody will get to unless we point people at it, we should make it a recommended task ;)

**Comment by ilicfilip** [comment]
Currently all options are assigning custom taxonomy term to the (selected) pages, so if user doesn't assign any page to a specific page type there will be nothing to check against if settings are saved or not.

Maybe we can add new entry to the `progress_planner_settings` option for that?

**Comment by aristath** [comment]
Hmmm we could perhaps use the `progress_planner_pro_license_key` setting from https://github.com/Emilia-Capital/progress-planner/pull/176... If the value is false then the form hasn't been saved. 🤔 
```php
switch ( \get_option( 'progress_planner_pro_license_key', false ) {
  case false:
    // Form has never been saved.
    break;

  case '':
    // Form has been saved but no license key was entered.
    break;

  default:
    // There is a license key entered, check if valid.
}

**Comment by ilicfilip** [comment]
Sure, we just need to check if that option entry is not false (in order to check if this task is completed or not)?

If the `progress_planner_pro_license_key` is definitely going to be added, I can cherry pick related code to the new branch and start implementation.

**Comment by aristath** [comment]
We could also merge that PR and just add `display:none` to that section... This way the input will be submitted but the field will be hidden until we're ready to show it 🪓
