### ISSUE TITLE
Auto-save changes on the settings page instead of having the click the save button

### ISSUE THREAD

**Issue by tacoverdo** [Emilia-Capital/progress-planner#156]
## Is your feature request related to a problem? Please describe.
On an average screen, the current settings page of PP continues below the fold. As a result, it's not very obvious there is a save button on the page that is required to save any changes to the settings. 

![Image](https://github.com/user-attachments/assets/a6313159-365d-4871-bf9a-b4987eaf9d80)
_Example of the settings page continuing below the fold_

## Describe the solution you'd like
I'd like to see the settings page auto save its settings when relevant changes are made. This could avoid confusion with customers. Ideally, the page would then also show a warning when one tries to leave the page with 'unfinished' or incomplete settings. 

### Example
Setting a blog page. 

![Image](https://github.com/user-attachments/assets/9255966d-9db4-4f17-ada8-92a78ea763e5)
_State of the settings page when visiting it_

![Image](https://github.com/user-attachments/assets/b3f479a2-cacb-44c5-8c84-ac8aacc5d42a)
_Setting the page is automatically saved_

![Image](https://github.com/user-attachments/assets/2d7e78a1-33de-4cca-a607-f7decfadcec0)
_Setting the page hasn't been fully completed (page missing from dropdown), which means the page should throw a notification when you're trying to leave it._

## Why do you think this feature is something we should consider for this plugin?
I feel it would make the settings page less prone to (human) error as it always gets saved after making changes.

**Comment by aristath** [comment]
Keep in mind that these will not be the only settings on that page.
Right now these are the only ones that exist, but soon we'll be adding more options there (such as license keys, site-scanning and more)
Though it makes sense to do it now that we only have radio-selects, it won't be the case once we have text-inputs etc for the other options.

**Comment by ilicfilip** [comment]
It was decided not to do auto save, we're keeping the Save button.
