### ISSUE TITLE
Password reset link showing as invalid

### ISSUE THREAD

**Issue by jdevalk** [Emilia-Capital/progress-planner#31]
Going through onboarding, people try to reset their password on progressplanner.com.

When they notice the message showing an account created successfully, they immediately try to reset the password and end up on [this page](https://progressplanner.com/wp-login.php?action=lostpassword&error=invalidkey); with the message "Error: Your password reset link appears to be invalid. Please request a new link below.".

I think:

- We shouldn't show that link during onboarding. We _should_ say that we are creating an account.
- We should send them an email after onboarding saying that we created an account for them on progressplanner.com, and how they can reset their password. Feel free to ping Iris & Marieke for copy.
- We should style the login page as Progress Planner not as Emilia Capital :)

Reported by both @josevarghese and @tacoverdo

**Comment by aristath** [comment]
Fixed in #35
