### ISSUE TITLE
Settings Page - make Plan and Assign features work

### ISSUE THREAD

**Issue by ilicfilip** [Emilia-Capital/progress-planner#96]
Settings page is now added to the Free version, it was done by moving necessary logic from the Pro version.

Currently the only setting section we have is "Your pages". Selecting pages from the dropdown works (behind the scenes term from specific taxonomy is assigned to that page), but logic for the Plan and Assign features is still missing.

For example: ![Image](https://github.com/user-attachments/assets/2913b0d6-b47a-4b6e-b23b-5f2b46a2d08d)

**Comment by aristath** [comment]
Closing this one, as these features will not be implemented yet.
