### ISSUE TITLE
Enabling more post types is not working

### ISSUE THREAD

**Issue by jeroenrotty** [Emilia-Capital/progress-planner#98]
* [x] I've read and understood the [contribution guidelines](https://github.com/Emilia-Capital/.github/blob/main/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Step-by-step reproduction instructions
1. Click checkbox to enable more post types like "Begrippen".
![Image](https://github.com/user-attachments/assets/ab4ab571-0f08-4828-985b-a152021da153)
2. Hit Save changes.
3. Page reload, open the Settings again.
4. See the post type not being enabled.

#### Expected results
The post type to be enabled.

#### Actual results
It was not.

**Comment by ellegaarddk** [comment]
I'm seeing the same - different CPT's but same problem. 
I can't make any changes to the post types, not even disable posts or pages.

I also see Elements (from Elementor) in the list. Is that intended?

**Comment by jeroenrotty** [comment]
Elements not being listed is probably because the Post Type is not a public one.

**Comment by ellegaarddk** [comment]
Elements ARE in the list to choose from. I don't think they were supposed to be there.
![Image](https://github.com/user-attachments/assets/22ae2ee4-7504-4661-9f49-6e94dcd02b5e)

**Comment by ellegaarddk** [comment]
https://github.com/user-attachments/assets/1a2784a2-4053-4dca-bbc6-42863669fd8c

**Comment by aristath** [comment]
Thank you for reporting this @jeroenrotty! 🙇 
The issue was fixed in https://github.com/Emilia-Capital/progress-planner/pull/93 and will be included in the next release, so I'll go ahead and close this ticket 🎉
