### ISSUE TITLE
To-do list item not draggable, but it has such icon on the left

### ISSUE THREAD

**Issue by jeroenrotty** [Emilia-Capital/progress-planner#99]
* [x] I've read and understood the [contribution guidelines](https://github.com/Emilia-Capital/.github/blob/main/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### To Reproduce
1. Hover a to-do list item
2. See a icon on the left to drag up or down
3. Experience it is not draggable

#### Expected results
Draggable.

#### Actual results
It is not.

### Screenshots, screen recording, code snippet
![Image](https://github.com/user-attachments/assets/5c50f9c6-cfab-47e7-ad07-c397e3fde077)

**Comment by ilicfilip** [comment]
As far I remember this was fixed, but we also changed to the up / down arrows instead of dragging.
![Image](https://github.com/user-attachments/assets/647e0ab9-58c3-4009-8bdd-de00e93b214f)

(I checked widget both on PP and Dashboard pages and it is working in both places).
